In [1]:
import cv2
import numpy as np

In [2]:
im1=cv2.imread("C:/Users/SN115/Pictures/yk/panda.jpg")

In [3]:
im1

array([[[  6,   0,   1],
        [  3,   1,   1],
        [  0,   1,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  7,   0,   0],
        [  6,   1,   2],
        [  5,  10,   9],
        ...,
        [  6,   6,   6],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  5,   0,   0],
        [  2,   0,   0],
        [  0,   1,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[203, 231, 231],
        [203, 231, 231],
        [203, 231, 231],
        ...,
        [  0,  60,  49],
        [  0,  62,  51],
        [  0,  62,  51]],

       [[250, 255, 255],
        [250, 255, 255],
        [250, 255, 255],
        ...,
        [ 33,  80,  72],
        [ 29,  78,  70],
        [ 29,  78,  70]],

       [[ 42,  47,  48],
        [ 42,  47,  48],
        [ 42,  47,  48],
        ...,
        [  3,  20,  16],
        [  0,  20,  15],
        [  0,  20,  15]]

In [4]:
height,width=im1.shape[:2]
print(height)
print(width)

478
850


In [5]:
cent=(height/2,width/2)
cent

(239.0, 425.0)

In [6]:
rotation_matrix=cv2.getRotationMatrix2D(center=cent,angle=27,scale=0.2)

In [7]:
print(rotation_matrix)

[[ 1.78201305e-01  9.07980999e-02  1.57820696e+02]
 [-9.07980999e-02  1.78201305e-01  3.70965191e+02]]


In [8]:
rotated_im1=cv2.warpAffine(src=im1, M=rotation_matrix,dsize=(width,height))

In [ ]:
cv2.imshow('Original image',im1)
cv2.waitKey(0)
cv2.imshow('Rotated image',rotated_im1)
cv2.waitKey(0)
cv2.destroyAllWindows()

# translation matrix

In [9]:
tx,ty=width/2,height/2

In [10]:
Translation_matrix=np.array([[1,0,tx],[0,1,ty]])

In [11]:
Translation_matrix

array([[  1.,   0., 425.],
       [  0.,   1., 239.]])

In [12]:
Trans_im1=cv2.warpAffine(src=im1, M=rotation_matrix,dsize=(width,height))

In [ ]:
cv2.imshow('Original image',im1)
cv2.waitKey(0)
cv2.imshow('Rotated image',Trans_im1)
cv2.waitKey(0)
cv2.destroyAllWindows()