# K-Means clustering

In [31]:
import cv2 
import numpy as np

In [2]:
img = cv2.imread("C:/Users/SN115/Pictures/yk/jkjk.png")
img

array([[[175, 192, 205],
        [174, 192, 204],
        [172, 193, 203],
        ...,
        [187, 140,  77],
        [187, 140,  77],
        [218, 193, 159]],

       [[175, 192, 205],
        [174, 192, 205],
        [173, 193, 204],
        ...,
        [187, 141,  78],
        [187, 141,  78],
        [218, 194, 159]],

       [[177, 193, 206],
        [175, 193, 206],
        [173, 194, 204],
        ...,
        [189, 143,  80],
        [189, 143,  79],
        [219, 194, 160]],

       ...,

       [[  7,   9,  10],
        [  7,   9,  10],
        [  7,   9,  10],
        ...,
        [ 23,  18,  15],
        [ 23,  18,  15],
        [129, 127, 125]],

       [[  8,  10,  11],
        [  8,  10,  11],
        [  8,  10,  11],
        ...,
        [ 23,  18,  15],
        [ 23,  18,  15],
        [129, 127, 125]],

       [[  9,  11,  12],
        [  8,  10,  11],
        [  8,  10,  11],
        ...,
        [ 23,  18,  15],
        [ 23,  18,  15],
        [129, 127, 125]]

# rgb conversion 

In [3]:
imgrgb = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

# reshape

In [4]:
vec = imgrgb.reshape((-1,3))
vec

array([[205, 192, 175],
       [204, 192, 174],
       [203, 193, 172],
       ...,
       [ 15,  18,  23],
       [ 15,  18,  23],
       [125, 127, 129]], dtype=uint8)

# float conversion

In [5]:
vec =  np.float32(vec)
vec

array([[205., 192., 175.],
       [204., 192., 174.],
       [203., 193., 172.],
       ...,
       [ 15.,  18.,  23.],
       [ 15.,  18.,  23.],
       [125., 127., 129.]], dtype=float32)

# iteration termination criteria

In [11]:
 Criteria = (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER, 100, 1)

# cluster condition

In [12]:
K = 3
attempts=100

# k-means clustering

In [29]:
compactness,label,center =cv2.kmeans(vec,K,None,Criteria,attempts,cv2.KMEANS_PP_CENTERS)
center

array([[ 15.989895,  20.528234,  22.902605],
       [193.84001 , 179.57582 , 163.83241 ],
       [ 58.245613,  95.50093 , 108.00922 ]], dtype=float32)

In [34]:
center=np.uint8(center)
center

array([[ 15,  20,  22],
       [193, 179, 163],
       [ 58,  95, 108]], dtype=uint8)

# flattening and reshape

In [35]:
res = center[label.flatten()]
res_img = res.reshape((imgrgb.shape))
res_img

array([[[193, 179, 163],
        [193, 179, 163],
        [193, 179, 163],
        ...,
        [ 58,  95, 108],
        [ 58,  95, 108],
        [193, 179, 163]],

       [[193, 179, 163],
        [193, 179, 163],
        [193, 179, 163],
        ...,
        [ 58,  95, 108],
        [ 58,  95, 108],
        [193, 179, 163]],

       [[193, 179, 163],
        [193, 179, 163],
        [193, 179, 163],
        ...,
        [ 58,  95, 108],
        [ 58,  95, 108],
        [193, 179, 163]],

       ...,

       [[ 15,  20,  22],
        [ 15,  20,  22],
        [ 15,  20,  22],
        ...,
        [ 15,  20,  22],
        [ 15,  20,  22],
        [ 58,  95, 108]],

       [[ 15,  20,  22],
        [ 15,  20,  22],
        [ 15,  20,  22],
        ...,
        [ 15,  20,  22],
        [ 15,  20,  22],
        [ 58,  95, 108]],

       [[ 15,  20,  22],
        [ 15,  20,  22],
        [ 15,  20,  22],
        ...,
        [ 15,  20,  22],
        [ 15,  20,  22],
        [ 58,  95, 108]]

# image

In [36]:
cv2.imshow('Original' ,img)
cv2.imshow('segmented' ,res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()